### ISSUE TITLE
Chart not rendering in view

### ISSUE THREAD

**Issue by funkdified** [michelson/lazy_high_charts#181]
The div is appearing in the HTML, and the javascript also appears in the source... Any idea why I am still seeing nothing on the page? 

**NOTE: Manually running the js in the console causes the chart to render just fine**

View:

    <%= high_chart("some_id", @chart) %>

Controller:

    @chart = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(:text => "Population vs GDP For 5 Big Countries [2009]")
      f.xAxis(:categories => ["United States", "Japan", "China", "Germany", "France"])
      f.series(:name => "GDP in Billions", :yAxis => 0, :data => [14119, 5068, 4985, 3339, 2656])
      f.series(:name => "Population in Millions", :yAxis => 1, :data => [310, 127, 1340, 81, 65])

      f.yAxis [
        {:title => {:text => "GDP in Billions", :margin => 70} },
        {:title => {:text => "Population in Millions"}, :opposite => true},
      ]

      f.legend(:align => 'right', :verticalAlign => 'top', :y => 75, :x => -50, :layout => 'vertical',)
      f.chart({:defaultSeriesType=>"column"})
    end

Result in page view:

    <script type="text/javascript">
    (function() {
      var onload = window.onload;
      window.onload = function(){
        if (typeof onload == "function") onload();
                var options = { "title": { "text": "Population vs GDP For 5 Big Countries [2009]" },"legend": { "align": "right","verticalAlign": "top","y": 75,"x": -50,"layout": "vertical" },"xAxis": { "categories": [ "United States","Japan","China","Germany","France" ] },"yAxis": [ { "title": { "text": "GDP in Billions","margin": 70 } },{ "title": { "text": "Population in Millions" },"opposite": true } ],"tooltip": { "enabled": true },"credits": { "enabled": false },"plotOptions": { "areaspline": {  } },"chart": { "defaultSeriesType": "column","renderTo": "some_id" },"subtitle": {  },"series": [{ "name": "GDP in Billions","yAxis": 0,"data": [ 14119,5068,4985,3339,2656 ] },{ "name": "Population in Millions","yAxis": 1,"data": [ 310,127,1340,81,65 ] }] };
    
    window.chart_some_id = new Highcharts.Chart(options);
    
      };
    })()
    </script>
    <div id="some_id"></div>

**Comment by michelson** [comment]
do you have any js errors in browser console ?

**Comment by funkdified** [comment]
No, I checked :\

**Comment by funkdified** [comment]
I was able to get it working by doing this 
```
    window.setTimeout(function(){$('#right_audio').html("<%= j high_chart('review_audiogram_right', @audio_right) %>")}, 500);
    window.setTimeout(function(){$('#left_audio').html("<%= j high_chart('review_audiogram_left', @audio_left) %>")}, 500);
```

**Comment by michelson** [comment]
what happens if you put the js after the div ? I think that is the problem

**Comment by funkdified** [comment]
The div is being created by the gem no?

**Comment by funkdified** [comment]
I tried this.. still no dice
```
          <div id="left_audio" class='col-md-6' style="margin-left: -8px;"> </div>
          <div id="right_audio" class='col-md-6' style="margin-left: -8px;"></div>
          <%= high_chart("right_audio", @audio_right) %>
          <%= high_chart("left_audio", @audio_left) %>
```

**Comment by michelson** [comment]
that´s odd, maybe you can try the example apps to test the expected behavior to see if there is something broken in your implementation

**Comment by funkdified** [comment]
Yes, I tried it with the basic example above and that didn't work .. 

I think something might be broken somewhere.. Not sure what.. Just upgraded to Rails 4 and Bootstrap 3... and some other gems needed to be upgraded as well. Who knows...

**Comment by michelson** [comment]
I've already tried the dummy app , located in https://github.com/michelson/lazy_high_charts/tree/master/spec/dummy_rails and works perfectly fine , rails 4.0.2. have you tried that app ?

**Comment by michelson** [comment]
@funkdified , try update highcharts js sources , it should work.

please reopen if the problem still persists

best!
