### ISSUE TITLE
set backgroundColor failed!

### ISSUE THREAD

**Issue by liuzxc** [michelson/lazy_high_charts#182]
I want to change high chart background color, but doesn't work.

```ruby
@chart = LazyHighCharts::HighChart.new('graph') do |f|
      f.chart({:backgroundColor => '#FCFFC5'})
.............
end
```

**Comment by xiaods** [comment]
could you please inspect the rendered javascript, check if the backgroudColor is left. then feedback to here. thanks a lot.

**Comment by liuzxc** [comment]
(function() {
          var onload = window.onload;
          window.onload = function(){
            if (typeof onload == "function") onload();
                    var options = { "title": { "text": "\u6bcf\u65e5\u8d44\u6e90\u8d70\u52bf\u56fe" },"legend": { "align": "right","verticalAlign": "top","y": 75,"x": -50,"layout": "vertical" },"xAxis": { "categories": [ "01-13","01-14","01-15","01-16","01-17","01-18","01-19","01-20","01-21","01-22","01-23","01-24","01-27" ] },"yAxis": [ [ { "title": { "text": "gold" } },{ "title": { "text": "wood" } },{ "title": { "text": "food" } },{ "title": { "text": "stone" } } ] ],"tooltip": { "enabled": true },"credits": { "enabled": false },"plotOptions": { "areaspline": {  } },"chart": { "defaultSeriesType": "column","renderTo": "some_id" },"subtitle": {  },"exporting": { "filename": "2015-01-28" },"series": [{ "name": "gold","type": "spline","data": [ 2700,2800,2900,3000,3100,3200,3300,3400,3500,3600,3700,3800,22270500 ] },{ "name": "wood","type": "spline","data": [ 3200,3300,3400,3500,3600,3700,3800,3900,4000,4100,4200,4300,22585500 ] },{ "name": "food","type": "spline","data": [ 2200,2300,2400,2500,2600,2700,2800,2900,3000,3100,3200,3300,21955500 ] },{ "name": "stone","type": "spline","data": [ 3700,3800,3900,4000,4100,4200,4300,4400,4500,4600,4700,4800,22900500 ] }] };
        
        window.chart_some_id = new Highcharts.Chart(options);

          };
        })()

**Comment by xiaods** [comment]
@liuzxc not found backgroundColor keyword in your paste javascript code. are you sure if it correct?

**Comment by liuzxc** [comment]
sorry，it is my fault. I set the `f.chart` twice.
