### ISSUE TITLE
Documentation not available for adding icon in Pie Chart

### ISSUE THREAD

**Issue by muhammad-irfan-arbisoft** [michelson/lazy_high_charts#184]
There is no proper documentation available on official site of HighCharts and also no support for icon on pie charts. Suppose I want to build a pie chart with this style, I've googled for about 8 hours and didn't find any solution on how to add icons on pie charts. Official site also have no proper documentation for adding the icons on Pie Charts.

![screen shot 2015-04-03 at 12 09 39 pm](https://cloud.githubusercontent.com/assets/9190955/6979521/91f97824-d9fe-11e4-953a-1ed957fdde25.png)

**Comment by michelson** [comment]
hi @muhammad-irfan-arbisoft 
maybe Highcharts not supports that kind of chart , you should ask directly in highcharts forum.

regards
