### ISSUE TITLE
Example: Clickable bar chart

### ISSUE THREAD

**Issue by paradoxon82** [michelson/lazy_high_charts#195]
In the example for a clickable bar chart, there is an annotation that says
*Warning: the controller returns an error stating js_function is undefined.*
And this is exactly what happens.

Does that mean embedded javascript does not work in this gem? Or is it possible to make it work?

**Comment by xiaods** [comment]
need a PR?

**Comment by paradoxon82** [comment]
Yes, I can try to fix it.

**Comment by xiaods** [comment]
@paradoxon82 Cool, any question, please at me.

**Comment by paradoxon82** [comment]
I figured out he problem, it is working for me now.
It was just an issue with the example in the wiki.
I can change the example to a working one.

**Comment by paradoxon82** [comment]
I have edited the wiki. The example should work now.

**Comment by xiaods** [comment]
thanks @paradoxon82
