### ISSUE TITLE
Uninitialized constant LazyHighCharts::HighChartGlobals

### ISSUE THREAD

**Issue by excel-tricks** [michelson/lazy_high_charts#204]
After copying and pasting the sample code from the ReadMe, I come across the error `uninitialized constant LazyHighCharts::HighChartGlobals` when loading the page. If I comment out the code for the globals in the controller and view, the chart loads fine.

Also, if I open up a console, I can type `@chart = LazyHighCharts::HighChart.new('graph')` and get a new chart just fine. However, when I try to run `@global = LazyHighCharts::HighChartGlobals.new`, I get the same `uninitialized constant` error.

**Comment by kntmrkm** [comment]
same here.

version 1.5.4 does not include `high_chart_globals.rb`.

So, we should use like below.

```
gem 'lazy_high_charts', github: 'michelson/lazy_high_charts'
```

**Comment by excel-tricks** [comment]
@kntmrkm That worked great for me. I was facing the same issue, but solved it with:

    gem 'lazy_high_charts', github: 'michelson/lazy_high_charts'

Strange how there's a difference between the files on Ruby Gems versus GitHub.

**Comment by michelson** [comment]
Hi , sorry for the inconvenience , the master brach (v.1.5.5) was not released, until today, 

please update your dependences and try it out, it globals settings will work now

reopen if you find more issues on this

best!
