### ISSUE TITLE
Annotations with High Stock

### ISSUE THREAD

**Issue by tunamonster** [michelson/lazy_high_charts#208]
Hi, I would like to add annotations to my high stocks chart, but I am having trouble passing the correct commands.
Correct code for the JS lib:
`series: [{
                name: 'Series name',
                data: data,
                id: 'dataseries',               
            }, {
                type: 'flags',
                name: 'Flags on series',
                data: [{
                    x: lastDate - 60 * days,
                    title: 'On series'
                }],
                onSeries: 'dataseries',
                shape: 'squarepin'
            }]`

My rails attempt:

  `f.series((name: 'sum', data: @t_data, id: 'dataseries'),(type: "flags", data[x:1456093403000, title: 'D', text: 'ooo'], onSeries: 'dataseries'))
`
It does not seem to accept the , after the first parentheses close
`syntax error, unexpected ',', expecting ')' f.series((name: 'sum', data: @t_data, id: 'dataseri... ^ `

Thanks

**Comment by michelson** [comment]
yup , it's not LazyHighCharts error , it's a ruby syntax error
please check out wiki page, https://github.com/michelson/lazy_high_charts/wiki/Combination-Chart

best
