### ISSUE TITLE
Do I need a Highcharts licence?

### ISSUE THREAD

**Issue by DanTaiko** [michelson/lazy_high_charts#216]
Hi,

Your gem is great. And it has fully filled my needs for the charts.

I'm using the charts in our company website section that is available for the company staff by a login. Should I buy a Highcharts licence in addition to the MIT licence on your gem?

Thanks in advance.

**Comment by xiaods** [comment]
for Highcharts usage, u need consult Highcharts guys to confirm the status.

**Comment by DanTaiko** [comment]
Thanks.

**Comment by michelson** [comment]
http://www.highcharts.com/products/highcharts
