### ISSUE TITLE
Problem with defer loading in Rails

### ISSUE THREAD

**Issue by kosappi** [michelson/lazy_high_charts#253]
If `defer` attribute is given to `javascript_include_tag` in Rails, no chart is drawn.

When I execute `Highcharts.chart(…` from devtool of the browser, it is drawn, so I expect that there is a problem with the execution timing.

---

This problem did not occur with using `addEventListener` instead of `window.onload`.
So I committed my fix to forked repository.
https://github.com/kosappi/lazy_high_charts/commit/620180d664b1987cebec3defbd8e23cba4fbad00
I tested this commit with my Rails application.

---

I completed the 4 steps below:

- [x] Fork the project -> https://github.com/kosappi/lazy_high_charts
- [x] Do your changes and commit them to your repository -> https://github.com/kosappi/lazy_high_charts/commit/620180d664b1987cebec3defbd8e23cba4fbad00
- [x] Test your changes. We won't accept any untested contributions (except if they're not testable).
- [x] Create an issue with a link to your commits.

via: https://github.com/michelson/lazy_high_charts#contributing

**Comment by xiaods** [comment]
welcome pr on this patch.

**Comment by kosappi** [comment]
@xiaods 

Thank you for reading this issue.

I created pr.
https://github.com/michelson/lazy_high_charts/pull/254
